services:
  app:
    build: .
    container_name: ezexpense
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data
    environment:
      - APP_SECURITY_JWT_SECRET=f41933ce671ed4a0f938b2b4d43e7614cb3ddc520a674210e4c0b625351f4eff

volumes:
  data:
