server:
  host: "0.0.0.0"
  port: 8080

database:
  path: "./data/ezexpense.db"

security:
  jwt_secret: "f41933ce671ed4a0f938b2b4d43e7614cb3ddc520a674210e4c0b625351f4eff"
  jwt_expire_days: 7

cors:
  origins:
    - "*"
