"""init

Revision ID: 18bd2b52ba1e
Revises: 
Create Date: 2026-05-12 17:03:16.947182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bd2b52ba1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_uid_deleted', 'expense_category', ['uid', 'deleted', 'display_order'], unique=False)
    op.create_table('expense_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_uid_deleted', 'expense_tag', ['uid', 'deleted', 'display_order'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('transaction_time', sa.Integer(), nullable=False),
    sa.Column('timezone_offset', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expense_uid_deleted_category', 'expense', ['uid', 'deleted', 'category_id', 'transaction_time'], unique=False)
    op.create_index('idx_expense_uid_deleted_time', 'expense', ['uid', 'deleted', 'transaction_time'], unique=False)
    op.create_table('expense_tag_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['expense_tag.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'tag_id')
    )
    op.create_index('idx_tag_index_expense', 'expense_tag_index', ['expense_id'], unique=False)
    op.create_index('idx_tag_index_uid_tag', 'expense_tag_index', ['uid', 'tag_id', 'expense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_index_uid_tag', table_name='expense_tag_index')
    op.drop_index('idx_tag_index_expense', table_name='expense_tag_index')
    op.drop_table('expense_tag_index')
    op.drop_index('idx_expense_uid_deleted_time', table_name='expense')
    op.drop_index('idx_expense_uid_deleted_category', table_name='expense')
    op.drop_table('expense')
    op.drop_index('idx_tag_uid_deleted', table_name='expense_tag')
    op.drop_table('expense_tag')
    op.drop_index('idx_category_uid_deleted', table_name='expense_category')
    op.drop_table('expense_category')
    op.drop_table('user')
    # ### end Alembic commands ###
